// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApjeZK5rVKt2NK4P5oFdSwZHc5S38xA9I',
    appId: '1:693199625118:web:5eb9a028a13f56a1f4948f',
    messagingSenderId: '693199625118',
    projectId: 'msa-enforcer',
    authDomain: 'msa-enforcer.firebaseapp.com',
    storageBucket: 'msa-enforcer.appspot.com',
    measurementId: 'G-1BP3NNQKHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbohs28ZH_tR-PSap03-t9w0Pnhbh4CkM',
    appId: '1:693199625118:android:cc3859192d36cbf7f4948f',
    messagingSenderId: '693199625118',
    projectId: 'msa-enforcer',
    storageBucket: 'msa-enforcer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1wZ2A6hFp3s10KT5tj_b0R6sV9Hk_u4',
    appId: '1:693199625118:ios:3e96fff9460b48ecf4948f',
    messagingSenderId: '693199625118',
    projectId: 'msa-enforcer',
    storageBucket: 'msa-enforcer.appspot.com',
    iosBundleId: 'com.mcp.enforcer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1wZ2A6hFp3s10KT5tj_b0R6sV9Hk_u4',
    appId: '1:693199625118:ios:3e96fff9460b48ecf4948f',
    messagingSenderId: '693199625118',
    projectId: 'msa-enforcer',
    storageBucket: 'msa-enforcer.appspot.com',
    iosBundleId: 'com.mcp.enforcer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApjeZK5rVKt2NK4P5oFdSwZHc5S38xA9I',
    appId: '1:693199625118:web:51eae0f145f64e8ff4948f',
    messagingSenderId: '693199625118',
    projectId: 'msa-enforcer',
    authDomain: 'msa-enforcer.firebaseapp.com',
    storageBucket: 'msa-enforcer.appspot.com',
    measurementId: 'G-9HWN4KE68G',
  );
}
